# Generated by Django 6.0 on 2025-12-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
    ]
