# Generated by Django 6.0 on 2025-12-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر طلب', 'verbose_name_plural': 'عناصر الطلب'},
        ),
    ]
